name: 'Code - Create new release'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: 'develop'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Switch branch
        run: |
          if [[ "develop" == "$version" ]]; then
            git checkout --track origin/develop
            git pull
          else
            git config user.name github-actions
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git checkout --track origin/develop
            git pull
            git checkout main
            git merge develop
          fi
        env:
          version: ${{ github.event_name == 'schedule' && 'develop' || github.event.inputs.version }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, zip, bcmath
      - name: Replace version
        id: replace-version
        uses: JC5/firefly-iii-dev@v34
        with:
          action: 'ff3:version'
          output: ''
        env:
          FIREFLY_III_ROOT: /github/workspace
          GH_TOKEN: ""
          FF_III_VERSION: ${{ github.event_name == 'schedule' && 'develop' || github.event.inputs.version }}
      - name: Generate JSON v2
        id: json-v2
        uses: JC5/firefly-iii-dev@v34
        with:
          action: 'ff3:json-translations v2'
          output: ''
        env:
          FIREFLY_III_ROOT: /github/workspace
          GH_TOKEN: ''
      - name: Build new JS
        run: |
          pwd
          npm install
          npm run build
      - name: Run CI
        run: |
          composer validate --strict
          composer update --no-dev --no-scripts --no-plugins -q
          sudo chown -R runner:docker resources/lang
      - name: Zip release
        run: |
          pwd
          ls -lah
          zip -rq release.zip . -x "*.git*" "*.github*"
      - name: Release
        run: |
          sudo timedatectl set-timezone Europe/Amsterdam
          git config user.name github-actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git config advice.addIgnoredFile false

          if [[ "develop" == "$version" ]]; then
            [[ -z $(git status --untracked-files=normal --porcelain) ]] && echo "this branch is clean, no need to push..." && exit 0;
          fi

          git add -A
          if test -f "output.txt"; then
            git reset output.txt
          fi
          git commit -m "Auto commit for release '$version' on $(date +'%Y-%m-%d')" || true
          git push

          if [[ "develop" == "$version" ]]; then
            echo "Create nightly release."
            git tag -a $version-$(date +'%Y%m%d') -m "Nightly development release '$version' on $(date +'%Y-%m-%d')"
            git push origin $version-$(date +'%Y%m%d')
            gh release create $version-$(date +'%Y%m%d') -p --verify-tag \
              -t "Development release for $(date +'%Y-%m-%d')" \
              -n "Bi-weekly development release of Firefly III with the latest fixes, translations and features. This release was created on **$(date +'%Y-%m-%d')** and may contain bugs. Use at your own risk. Docker users can find this release under the \`develop\` tag."
            gh release upload $version-$(date +'%Y%m%d') release.zip
          else
            echo "Create default release."
            git tag -a $version -m "Here be changelog"
            git push origin $version
            gh release create $version -F output.txt -t "$version" --verify-tag
            gh release upload $version release.zip
            rm output.txt
            git checkout develop
            git merge main
            git push
          fi


        env:
          GH_TOKEN: ${{ github.token }}
          version: ${{ github.event_name == 'schedule' && 'develop' || github.event.inputs.version }}
